CHANGELOG.md, pom.xml, project.clj, src/wowman/curseforge.clj, src/wowman/http.clj, src/wowman/logging.clj, src/wowman/specs.clj, src/wowman/ui/gui.clj, test/wowman/http_test.clj
where a curseforge 404 response silently killed the async download thread
=> fixes issue#16

CHANGELOG.md, pom.xml, project.clj, src/wowman/core.clj, src/wowman/toc.clj, src/wowman/ui/gui.clj, test/wowman/toc_test.clj
* 'gridbug' fix
* ':open' addon directory selection fix
* missing 'Title' in .toc file fix
=> 0.9.1 prep

TODO.md, src/wowman/core.clj, test/fixtures/dummy-catalog--single-entry.json, test/wowman/core_test.clj
=> attempts to download and load catalog again when json file is corrupt

src/wowman/core.clj, src/wowman/utils.clj
fixes a bug where the .sql files were being read at runtime rather than compile time
=> static slurp

src/wowman/catalog.clj, src/wowman/curseforge_api.clj, src/wowman/main.clj, src/wowman/specs.clj, src/wowman/wowinterface.clj, src/wowman/wowinterface_api.clj, test/fixtures/wowinterface-api--addon-details.json, test/wowman/curseforge_api_test.clj, test/wowman/wowinterface_api_test.clj, test/wowman/wowinterface_test.clj, update-test-fixtures.sh
=> adds 'source' properties to wowinterface and curse catalog items

TODO.md, src/wowman/wowinterface.clj, test.sh, test/wowman/wowinterface_test.clj
=> Fix: wowinterface classic addons fix

.travis.yml, TODO.md, release.sh
> will prevent me from having to download release to generate a sumfile
also, security n stuff
=> travis, adds a 'release' script that generates a sha256 hash

src/wowman/core.clj, test/wowman/core_test.clj
addresses issue: https://github.com/ogri-la/wowman/issues/121
* addons missing nfo files are not upgraded.
* nfo files that are still not valid even after an attempted upgrade are deleted.
=> nfo file upgrade fixes

project.clj, src/wowman/catalog.clj, src/wowman/core.clj, src/wowman/utils.clj, test/wowman/core_test.clj, test/wowman/utils_test.clj
* fix for issue #129, too-long description borks db
=> fix for issue 129

TODO.md, run-tests.sh, src/strongbox/config.clj, src/strongbox/core.clj, src/strongbox/specs.clj, src/strongbox/ui/gui.clj, test/fixtures/user-config-1.0.json, test/strongbox/config_test.clj, test/strongbox/core_test.clj
=> Remember the selected addon directory.

src/strongbox/catalogue.clj, src/strongbox/config.clj, src/strongbox/core.clj, src/strongbox/specs.clj, src/strongbox/ui/cli.clj, src/strongbox/wowinterface.clj, test/fixtures/catalogue--v2--curseforge.json, test/fixtures/catalogue--v2--tukui.json, test/fixtures/catalogue--v2--wowinterface.json, test/fixtures/user-config-1.0.json, test/strongbox/catalogue_test.clj, test/strongbox/cli_test.clj, test/strongbox/core_test.clj, test/strongbox/test_helper.clj
=> strongbox catalogue generation

TODO.md, src/strongbox/catalogue.clj, src/strongbox/config.clj, src/strongbox/core.clj, src/strongbox/nfo.clj, src/strongbox/ui/gui.clj, src/strongbox/utils.clj
non-destructive migration of wowman settings and configuration to strongbox
=> Migrate wowman

src/wowman/ui/gui.clj
Fixes: https://github.com/ogri-la/strongbox/issues/149
=> Fix for issue #149

TODO.md, src/strongbox/core.clj, src/strongbox/ui/gui.clj, test/strongbox/gui_test.clj, test/strongbox/test_helper.clj
* adds 'latest update' fix + tests
=> bug fix, 'latest update' gui crash

.joker, lint.sh, src/strongbox/catalogue.clj, src/strongbox/config.clj, src/strongbox/core.clj, src/strongbox/http.clj, src/strongbox/specs.clj, src/strongbox/tags.clj, src/strongbox/tukui_api.clj, src/strongbox/ui/gui.clj, src/strongbox/utils.clj, src/strongbox/wowinterface.clj, test/strongbox/core_test.clj, test/strongbox/db_test.clj, test/strongbox/nfo_test.clj, test/strongbox/toc_test.clj, test/strongbox/zip_test.clj
adds linting provided by joker
addresses lint issues raised by switching to openjdk 11
=> adds linting provided by joker.

CONTRIBUTING.md, TODO.md, cloverage.clj, src/strongbox/core.clj, src/strongbox/http.clj, src/strongbox/logging.clj, src/strongbox/main.clj, src/strongbox/ui/gui.clj, src/strongbox/wowinterface.clj, test/strongbox/http_test.clj, test/strongbox/main_test.clj
=> easier debugging

TODO.md, src/strongbox/addon.clj, src/strongbox/core.clj, src/strongbox/nfo.clj, src/strongbox/ui/gui.clj, test/strongbox/core_test.clj, test/strongbox/nfo_test.clj
how the f did this pass testing and review?
=> ignore addons bug

src/strongbox/wowinterface.clj
*finally* fixes java8/11 datetime parsing bug.
I was catching the wrong exception.
=> wowi, datetime parse bug fixes

.travis.yml, TODO.md, build-linux-image.sh, release.sh, src/strongbox/main.clj, test/strongbox/gui_test.clj
sets default gui to javafx.
- swing gui can be accessed using --ui gui1
=> build on release

src/strongbox/core.clj, src/strongbox/db.clj, src/strongbox/ui/jfx.clj, test/strongbox/db_test.clj
issue: https://github.com/ogri-la/strongbox/issues/183
=> ignored addons are not matched to catalogue

project.clj
* project.clj, adds mac javafx libraries
=> mac, add javafx libraries to uberjar

TODO.md, src/strongbox/core.clj, src/strongbox/db.clj, src/strongbox/ui/cli.clj, src/strongbox/ui/jfx.clj, test/strongbox/cli_test.clj, test/strongbox/test_helper.clj
=> search results pagination

src/strongbox/tukui_api.clj, test/fixtures/tukui--addon-details-missing-patch.json, test/fixtures/tukui--addon-details.json, test/fixtures/tukui--classic-addon-details.json, test/strongbox/tukui_api_test.clj
=> tukui, fixes for changed API

TODO.md, src/strongbox/core.clj, src/strongbox/ui/cli.clj, src/strongbox/ui/jfx.clj
* `F5` and `View -> Refresh` now clear the http cache before checking for updates.
=> caching improvements

TODO.md, src/strongbox/core.clj
output file is written when running strongbox in debug mode *only*.
extra output contains OS, Java and JavaFX versions
=> debugging, adds more system properties to output file.

src/strongbox/core.clj, src/strongbox/specs.clj, src/strongbox/ui/cli.clj, src/strongbox/ui/jfx.clj, test/fixtures/user-config-3.2.json, test/strongbox/config_test.clj
=> Gui2 updateable colour tweak

.joker, TODO.md, project.clj, src/strongbox/http.clj, src/strongbox/ui/gui.clj, test/strongbox/http_test.clj
https://github.com/ogri-la/strongbox/issues/233
=> http, fixes url normalisation breaking specific requests

src/strongbox/ui/jfx.clj
the contents of those containers are sized much better now.
=> gui2, switched some vboxes to border-panes.

CHANGELOG.md, TODO.md, cloverage.clj, project.clj, src/strongbox/core.clj, src/strongbox/logging.clj, src/strongbox/main.clj, src/strongbox/ui/cli.clj, src/strongbox/ui/jfx.clj, test/strongbox/cli_test.clj, test/strongbox/jfx_test.clj, test/strongbox/logging_test.clj
4.0 styling to get it presentable before I release
- this will be an ongoing effort I think
- yeah, definitely need more padding between them
- buttons in the dark theme seem to have lost some definition in general and look ... smaller. they're not, I think it's highlighting/borders that are making them a bit 'off'.
- actually, there *is* something weird going on here. changing the border colour is affecting their width.
- going to leave the dark theme with slightly murky buttons for now. I suspect it's because I'm *not* using a dark theme for my desktop that the glare of the surrounding apps is making the buttons harder to discern.
- particularly noticable with dark theme and emboldened links
- they seem to cause the slightest amount of horizontal scrolling
- I've tweaked a few of them, …
=> 4.0 style tweaks

CHANGELOG.md, TODO.md, src/strongbox/catalogue.clj, src/strongbox/constants.clj, src/strongbox/curseforge_api.clj, src/strongbox/specs.clj, src/strongbox/tukui_api.clj, src/strongbox/ui/jfx.clj, src/strongbox/utils.clj, src/strongbox/wowinterface.clj, test/fixtures/tukui--classic-tbc-addon-details.json, test/strongbox/curseforge_api_test.clj, test/strongbox/jfx_test.clj, test/strongbox/tukui_api_test.clj, test/strongbox/utils_test.clj, test/strongbox/wowinterface_test.clj
=>  adds classic (tbc) support

.gitignore, CHANGELOG.md, TODO.md, run-tests.sh, src/strongbox/constants.clj, src/strongbox/github_api.clj, src/strongbox/specs.clj, src/strongbox/toc.clj, src/strongbox/utils.clj, test/fixtures/github-repo-releases--mixed-game-tracks.json, test/strongbox/github_api_test.clj, test/strongbox/toc_test.clj, test/strongbox/utils_test.clj
=> github-api, adds classic-tbc support

CHANGELOG.md, TODO.md, src/strongbox/ui/jfx.clj
=> gui, search, adds 'install' button for each addon

CHANGELOG.md, TODO.md, src/strongbox/http.clj, src/strongbox/ui/jfx.clj, test/strongbox/http_test.clj
This is to improve the scenario where an addon host (Tukui for example ...) is responding but very very very slowly, making the app appear locked up.
=> HTTP timeout

CHANGELOG.md, README.md, TODO.md, src/strongbox/http.clj, src/strongbox/logging.clj, test/strongbox/http_test.clj
=> github auth

CHANGELOG.md, TODO.md, src/strongbox/core.clj, src/strongbox/db.clj, src/strongbox/http.clj, src/strongbox/ui/cli.clj, src/strongbox/ui/jfx.clj, test/strongbox/cli_test.clj, test/strongbox/core_test.clj, test/strongbox/http_test.clj
=> changing catalogue updates search results

CHANGELOG.md, TODO.md, src/strongbox/catalogue.clj, src/strongbox/core.clj, src/strongbox/http.clj, src/strongbox/joblib.clj, src/strongbox/ui/jfx.clj, test/strongbox/core_test.clj, test/strongbox/joblib_test.clj, test/strongbox/logging_test.clj
* tweaks to log messages.
* renamed `change-log-level!` to `set-log-level!`. I'm always having to remember what I called that fn ...
=> tweaks, bug fixes

CHANGELOG.md, TODO.md, release.md, src/strongbox/catalogue.clj, src/strongbox/http.clj, src/strongbox/specs.clj, test/strongbox/catalogue_test.clj, test/strongbox/core_test.clj, test/strongbox/github_api_test.clj, test/strongbox/http_test.clj
* better handling of failures when network not available.
* fixes minor bug with http/http-error
=> better handling of failures when network not available.

CHANGELOG.md, TODO.md, project.clj, src/strongbox/catalogue.clj, test/fixtures/catalogue--v2--wowinterface.json, test/fixtures/catalogue--v2.json
* some minor speed improvements to `data.json` ~but also new errors that need extra handling~ my test fixtures were bad! a missing comma snuck in and was copied and pasted to another fixture.
=> bumps dependencies

CHANGELOG.md, src/strongbox/core.clj, src/strongbox/specs.clj, src/strongbox/ui/cli.clj, src/strongbox/wowinterface_api.clj, test/fixtures/wowinterface--download-not-approved.html, test/strongbox/cli_test.clj, test/strongbox/wowinterface_api_test.clj
=> wowinterface, fixes case where a download is 'pending approval'

.joker, CHANGELOG.md, build-linux-image.sh, project.clj, src/strongbox/addon.clj, src/strongbox/http.clj, src/strongbox/specs.clj, src/strongbox/tukui_api.clj, src/strongbox/ui/jfx.clj, src/strongbox/utils.clj, src/strongbox/wowinterface.clj, src/strongbox/wowinterface_api.clj, src/strongbox/zip.clj
=> type hinting, covered some easy cases.

CHANGELOG.md, src/strongbox/db.clj
while searching ~16k addons for "world of warcraft"
99% ≤ 
209.45μs 
to
99% ≤ 
2.39μs
I knew it was slow, but damn ...
=> search, speeds search results up two orders of magnitude.

CHANGELOG.md, TODO.md, cloverage.clj, src/strongbox/catalogue.clj, src/strongbox/core.clj, src/strongbox/db.clj, src/strongbox/joblib.clj, src/strongbox/logging.clj, src/strongbox/main.clj, src/strongbox/tags.clj, src/strongbox/ui/cli.clj
trying to get at the heart of what is taking so long to switch between catalogues.
update: bunch of things but mostly catalogue validation.
=> Profile catalogue

CHANGELOG.md, TODO.md, java-src/splash/Main.java, java-src/splash/PreloadingApplication.java, java-src/splash/ProgressBarPreloader.java, project.clj
=> splash screen

CHANGELOG.md, TODO.md, src/strongbox/core.clj, src/strongbox/github_api.clj, src/strongbox/gitlab_api.clj, src/strongbox/http.clj, src/strongbox/ui/cli.clj, src/strongbox/ui/jfx.clj, test/strongbox/cli_test.clj, test/strongbox/core_test.clj, test/strongbox/release_json_test.clj, test/strongbox/test_helper.clj
For debugging only at this point. The 'refresh user catalogue' action isn't handling 404s very well and a few other things.
=> gui, adds a 'user-catalogue' pane.

CHANGELOG.md, TODO.md, src/strongbox/http.clj, test/strongbox/http_test.clj
=> http, fixes regression on backoff

CHANGELOG.md, README.md, TODO.md, src/strongbox/catalogue.clj, src/strongbox/constants.clj, src/strongbox/ui/jfx.clj, src/strongbox/utils.clj, test/strongbox/catalogue_test.clj
- so they'll never be green again :(
=> Curseforge cut-off

CHANGELOG.md, README.md, TODO.md, src/strongbox/config.clj, src/strongbox/specs.clj, src/strongbox/ui/cli.clj, src/strongbox/ui/jfx.clj, src/strongbox/utils.clj, test/strongbox/jfx_test.clj, test/strongbox/utils_test.clj
=> column presets

CHANGELOG.md, TODO.md, src/strongbox/github_api.clj, test/fixtures/github-catalogue--dummy.csv, test/strongbox/github_api_test.clj
=> github, catalogue parsing updated to support newer schema

CHANGELOG.md, TODO.md, src/strongbox/catalogue.clj, src/strongbox/core.clj, src/strongbox/curseforge_api.clj, src/strongbox/main.clj, src/strongbox/toc.clj, src/strongbox/ui/jfx.clj, src/strongbox/utils.clj, src/strongbox/wowinterface_api.clj, test/strongbox/catalogue_test.clj, test/strongbox/core_test.clj
=> replace multi-error messages with a single multi-line error message

CHANGELOG.md, TODO.md, src/strongbox/addon.clj, src/strongbox/catalogue.clj, src/strongbox/core.clj, src/strongbox/db.clj, src/strongbox/nfo.clj, src/strongbox/specs.clj, src/strongbox/ui/cli.clj, src/strongbox/ui/jfx.clj, src/strongbox/utils.clj, test/strongbox/cli_test.clj, test/strongbox/utils_test.clj
- does it need a label/caption/tooltip?
=> gui, search, add user-catalogue filter

CHANGELOG.md, TODO.md, src/strongbox/github_api.clj, src/strongbox/main.clj, src/strongbox/wowinterface.clj, test/strongbox/main_test.clj
=> GitHub catalogue fixes

.circleci/config.yml, CHANGELOG.md, src/strongbox/ui/jfx.clj
=> gui, adds 'Browse addon directory' option to 'File' menu.

CHANGELOG.md, TODO.md, src/strongbox/ui/jfx.clj, test/strongbox/utils_test.clj
*more* highlighted than the row's background colour changing...
=> gui, 'version' column now has value highlighted when updated available.

CHANGELOG.md, TODO.md, src/strongbox/ui/cli.clj
=> jfx, hard-refresh (ctrl-f5) now does a full refresh

CHANGELOG.md, TODO.md, src/strongbox/addon.clj, src/strongbox/core.clj, src/strongbox/specs.clj, src/strongbox/toc.clj, src/strongbox/utils.clj, test/fixtures/questie--invalid.toc, test/strongbox/core_test.clj, test/strongbox/test_helper.clj, test/strongbox/toc_test.clj
* toc, invalid toc data is now ignored
=> Questie problems

CHANGELOG.md, TODO.md, src/strongbox/catalogue.clj, src/strongbox/constants.clj, src/strongbox/specs.clj, src/strongbox/toc.clj, src/strongbox/ui/jfx.clj, src/strongbox/utils.clj, test/strongbox/curseforge_api_test.clj, test/strongbox/github_api_test.clj, test/strongbox/gitlab_api_test.clj, test/strongbox/utils_test.clj
=> support for wotlk-classic

src/strongbox/addon.clj, src/strongbox/catalogue.clj, src/strongbox/http.clj, src/strongbox/specs.clj, src/strongbox/tukui_api.clj, src/strongbox/ui/jfx.clj, src/strongbox/utils.clj, test/fixtures/tukui--classic-wotlk-addon-details.json, test/strongbox/catalogue_test.clj, test/strongbox/core_test.clj, test/strongbox/tukui_api_test.clj
=> tukui, support for wotlk-classic 

CHANGELOG.md, TODO.md, src/strongbox/constants.clj, src/strongbox/utils.clj, test/strongbox/curseforge_api_test.clj, test/strongbox/utils_test.clj
* utils, support for 10.0.0 and six digit interface versions.
=> dragonflight tweaks

TODO.md, src/strongbox/jfx.clj, src/strongbox/nfo.clj
=> gui, fixes bug where an ignored addon yields no mutual dependencies

CHANGELOG.md, TODO.md, src/strongbox/jfx.clj
=> gui, fixes tall messages that get truncated.

CHANGELOG.md, TODO.md, src/strongbox/jfx.clj
=> gui, fixes bug where the 'WoW' column has black text in dark mode

CHANGELOG.md, TODO.md, src/strongbox/cli.clj, src/strongbox/core.clj, src/strongbox/jfx.clj, src/strongbox/specs.clj, test/strongbox/cli_test.clj
=> gui, adds an 'any of' / 'all of' drop-down to tagged searches

CHANGELOG.md, TODO.md, build-linux-image.sh, project.clj, repl/strongbox/user.clj, src/strongbox/catalogue.clj, src/strongbox/core.clj, src/strongbox/jfx.clj, src/strongbox/main.clj, src/strongbox/specs.clj, src/strongbox/utils.clj, test/strongbox/core_test.clj, test/strongbox/utils_test.clj
=> image size and startup time improvements
