src/wowman/toc.clj
test/wowman/toc_test.clj

'Title' values in .toc files now require a leading space before detecting and stripping trailing version information

fixes issue#42

---

TODO.md
project.clj
resources/query--all-catalog.sql
resources/table--catalog.sql
resources/table--category.sql
src/wowman/core.clj
src/wowman/http.clj
src/wowman/ui/gui.clj
src/wowman/utils.clj
test/wowman/core_test.clj
test/wowman/toc_test.clj

big goals for this feature:
* code removal. I want to cut out loads of code that has grown obscure.
* make the intent of the remaining code *clearer*. 
* make searching addons faster and fuzzier. right now it's a simple "name starts with $userinput" filter. the most basic sql can handle better searching and faster
cons:
* it makes the distributable larger by 3MB
* it's going to touch a *lot* of otherwise stable code
* there is a slight pause of ~2 seconds while the ~10k addons, their categories and the associations are inserted. I have a `todo` in the bucket to start timing these operations to look for regressions and optimisations

database support

---

src/wowman/ui/gui.clj

Fixes case where entering a non-directory path (or just plain gibberish) in the addon-dir file picker causes a validation error further down than in should. It now displays an alert with the bad path that was chosen.
This is a nicer failure and may help Mac users whose file picker is behaving slightly differently than on Linux.

Fix: selecting a non-directory in the addon-dir picker now displays an alert

---

src/wowman/ui/gui.clj

':open' appears to force a different type of dialog that is better for selecting directories.
linux behaviour appears unchanged.

gui, addon-dir dialog changed to :open from "select" for mac users

---

src/wowman/core.clj
src/wowman/toc.clj
test/wowman/toc_test.clj

* adds a guard around toc/parse-addon-toc to prevent any failure in parsing from affecting the running of the program
* missing 'Title' values in .toc files are now replaced with the name of the addon dir with an asterisk

makes scraping .toc files a little safer

---

src/wowman/catalog.clj
src/wowman/core.clj
src/wowman/specs.clj
src/wowman/ui/gui.clj
test/wowman/core_test.clj

fixes two issues related to WoW game track in 0.9.0
* attempting to install an addon from the search pane that is classic-onlyinto an addon-dir that is 'retail'  (or vice versa) caused a fault
* attempting to re-install an addon that is classic-only into an addon-dir that is 'retail' (or vice versa) caused a fault
These bugs are due to new logic I hadn't anticipated. A match between an installed addon and the catalog may be found, but not necessarily a *release* of that addon matching the addon directory game track (default 'retail').

Issue 47 (again)

---

TODO.md
resources/table--catalog.sql
src/wowman/catalog.clj
src/wowman/core.clj
src/wowman/main.clj
src/wowman/specs.clj
src/wowman/ui/cli.clj
src/wowman/ui/gui.clj
src/wowman/utils.clj
test/wowman/cli_test.clj
test/wowman/core_test.clj
test/wowman/gui_test.clj
test/wowman/main_test.clj
test/wowman/test_helper.clj

This feature is an effort to reduce the default size of the catalog. 
* catalog is getting [large](https://github.com/ogri-la/wowman-data/releases) (at 5.42MB) as the different hosts add more addons and as I derive more fields to use (like `game-track-list` and `age` and `alt-name`). 
* It takes a few seconds to load all of these addons into the database when wowman is first started
* about half of this data are addons that haven't been updated in a long time and have a good chance of not working anymore.
* I don't want to remove the ability to use the full catalog if you really want to

Big catalog, Little catalog

---

src/wowman/core.clj
src/wowman/main.clj
test/wowman/core_test.clj
test/wowman/main_test.clj
test/wowman/test_helper.clj

The map of paths is now generated at app initialisation rather than on function call. This ties path access to app initialisation but provides improved isolation while testing because envvars are thread-local and the binding is lost if `paths` is later called from another thread other than the one the app was initialised on (which happens occasionally and when we least expect it).

fixed paths

---

src/wowman/ui/gui.clj

Using 'width 100%' had the effect of enlarging
components beyond the edges of the window
presumably because of the way insets are
applied to sub-components.
Also replaced a flow-panel with a mig-panel
to apply a maximum width to the add-on folder
selection dropdown, truncating the path.

Prevent clipping of various components

---

TODO.md
src/wowman/core.clj
src/wowman/github_api.clj
src/wowman/ui/gui.clj
test/wowman/github_api_test.clj

* addon may be successfully added to catalogue but may then fail to install.
* addon now uses data from the releases response to determine the source-id property, rather than derive it from the user input. This was leading to duplicate addons in user catalogue.
* catalogue is now reloaded when an addon is successfully added, regardless of whether it successfully installed or not

github addons, two bug fixes.

---

TODO.md
src/wowman/core.clj
src/wowman/ui/gui.clj
src/wowman/utils.clj
test/wowman/core_test.clj
test/wowman/curseforge_api_test.clj
test/wowman/gui_test.clj
test/wowman/test_helper.clj
test/wowman/utils_test.clj

* fixes bug with addons export ignoring path
* adds `:source-id` to data that is exported
todo

Fix: export addons bug

---

TODO.md
src/wowman/http.clj
test/wowman/http_test.clj

curse API provides download links like 
`https://edge.forgecdn.net/files/1/1/EveryAddon.zip`
rather than
`https://addons.cursecdn.com/files/2548/794/AR 4.5.7.3.zip`
that must be encoded.

Remove curse crap redirect strategy

---

src/wowman/core.clj
src/wowman/utils.clj
test/wowman/core_test.clj
test/wowman/test_helper.clj

* wowman now looks in a 'wowman' subdir when XDG paths specified
* empty XDG paths are ignored in favour of defaults

fix for XDG paths

---

TODO.md
src/wowman/core.clj
src/wowman/github_api.clj
src/wowman/http.clj
src/wowman/logging.clj
src/wowman/specs.clj
src/wowman/ui/gui.clj
src/wowman/utils.clj
test/wowman/core_test.clj
test/wowman/github_api_test.clj

* github-api calls are now cached. this is important because you get 60 requests/hour without an api token
todo:
---
- ^ it takes two requests to github to refresh a user catalogue addon with a cap of 60 requests/hour. one request is used looking up latest wowman release information. I've instead made a manual refresh button while I think about gradual updates a bit more.

user catalog refresh

---

TODO.md
src/wowman/config.clj
src/wowman/core.clj
src/wowman/main.clj
test/wowman/config_test.clj
test/wowman/core_test.clj

* moves configuration wrangling to separate file 'config.clj'
* directories that go missing no longer nuke user config

bug: disappearing config

---

TODO.md
src/wowman/core.clj
src/wowman/specs.clj
src/wowman/utils.clj
test/wowman/core_test.clj
test/wowman/utils_test.clj

* present in `0.10.*`
The data from the installed addon, like `description`, is overwritten by `nil` values when it leaves the database if it wasn't present in the catalogue. In fact, it looks like installed data is being supplanted entirely by the catalogue data after a match has been made.

Missing description regression

---

TODO.md
src/wowman/specs.clj
src/wowman/toc.clj
test/wowman/core_test.clj
test/wowman/toc_test.clj

* `X-WoWI-ID` and `X-Curse-Project-ID` are now detected in `.toc` files and used during reconcilation

adds curseforge and wowinterface source parsing in .toc files

---

TODO.md
src/wowman/core.clj
src/wowman/main.clj
src/wowman/nfo.clj
src/wowman/specs.clj
src/wowman/toc.clj
src/wowman/ui/gui.clj
test/wowman/core_test.clj
test/wowman/nfo_test.clj
test/wowman/toc_test.clj

ignore certain addons 

---

TODO.md
src/strongbox/core.clj
src/strongbox/toc.clj
test/strongbox/core_test.clj
test/strongbox/toc_test.clj

* toc no longer depends on nfo.
* toc+nfo merging logic moved into core

separate toc and nfo modules

---

TODO.md
src/strongbox/catalogue.clj
src/strongbox/core.clj
src/strongbox/curseforge_api.clj
src/strongbox/github_api.clj
src/strongbox/main.clj
src/strongbox/specs.clj
src/strongbox/tags.clj
src/strongbox/tukui_api.clj
src/strongbox/ui/gui.clj
src/strongbox/utils.clj
src/strongbox/wowinterface.clj
test/fixtures/import-export--user-catalogue.json
test/strongbox/catalogue_test.clj
test/strongbox/core_test.clj
test/strongbox/curseforge_api_test.clj
test/strongbox/github_api_test.clj
test/strongbox/http_test.clj
test/strongbox/tags_test.clj
test/strongbox/tukui_api_test.clj
test/strongbox/utils_test.clj
test/strongbox/wowinterface_api_test.clj

* removes the logic that merged the curse and wowi catalogues
* adds a `tag-list` alongside `category-list`

categories to tags

---

TODO.md
src/strongbox/config.clj
test/fixtures/user-config-0.10.json
test/fixtures/user-config-0.11.json
test/fixtures/user-config-0.12.json
test/strongbox/config_test.clj

a bug was found in a set of user configuration test fixtures that was introduced during the bulk renaming of 'catalog' to 'catalogue'.

User config fixture fix

---

src/wowman/ui/gui.clj

Handles case where java fails to detect a 'desktop'. Falls back to trying `xdg-open`, then `gnome-open` then `kde-open` before finally failing with an error message.

issue #138: failure to detect Desktop breaks links

---

TODO.md
project.clj
src/strongbox/core.clj
src/strongbox/db.clj
src/strongbox/github_api.clj
src/strongbox/ui/gui.clj
test/strongbox/core_test.clj

* not *all* slowness, it's still fundamentally a naive linear search using regexes over structs in memory, but the appearance of results is no longer tied to typing speed (results are updated asynchronously).
* hides some stacktraces that were appearing while testing - these were deliberate but potentially masking actual stacktraces happening in threads that aren't causing tests to fail
* bumps `eastwood`
* found a bug caught by an eastwood linter that was disabled. it wasn't a big deal, didn't affect anything, but was definitely incorrect

fixes slowness with searching.

---

TODO.md
src/strongbox/catalogue.clj
src/strongbox/db.clj
src/strongbox/tukui_api.clj
src/strongbox/ui/gui.clj

elvui fix 

---

TODO.md
src/strongbox/core.clj
src/strongbox/ui/gui.clj
test/strongbox/core_test.clj
test/strongbox/gui_test.clj

The `ignore?` value being returned by the selected rows from the gui is mangled and causing a crash when calling re-install.

bug, reinstall is busted

---

TODO.md
src/strongbox/core.clj
src/strongbox/ui/gui.clj
test/strongbox/core_test.clj

just found two bugs while messing about on an unconfigured instance

last minute bug fixes 

---

src/strongbox/core.clj
src/strongbox/ui/jfx.clj

* installed addons menu bar buttons now have a min-width to prevent truncation and ellipses.
* wow-dir dropdown now truncates from the left instead of the right.
* strongbox update button no longer takes up any width despite not being visible.
* minimum app width is now about ~500px
* [improved dark theme](https://github.com/ogri-la/strongbox/issues/192)
* empty installed and search tables now have better placeholder text

3.0 review feedback

---

src/strongbox/core.clj

Bumps the cutoff date for the 'short' catalogue from Legion (2016-08) to BfA (2018-08). This removes about ~3k addons that haven't been updated in ~2.5yrs.

reset short catalogue cutoff date

---

TODO.md
src/strongbox/addon.clj
src/strongbox/core.clj
src/strongbox/db.clj
src/strongbox/specs.clj
src/strongbox/toc.clj
test/strongbox/addon_test.clj
test/strongbox/toc_test.clj

Addons with crazy 'title' values in their tocs make it difficult to reconcile that addon against the catalogue. Some popular addons have their source and source-id hardcoded into strongbox.
* toc, aliases now hardcode 'source' and 'source-id' rather than 'name'. The lookup will be more accurate and it gets rid of an ':alias' key that was floating around, unspecced.

improved aliases

---

src/strongbox/core.clj
src/strongbox/main.clj
src/strongbox/ui/gui.clj

gui1, dynamic include of 'gui' ns from main.clj, disables ui restart.
this also means theme switching in the old ui has been disabled.

mac, crash fix

---

CHANGELOG.md
README.md
TODO.md
project.clj
src/strongbox/addon.clj
src/strongbox/core.clj
src/strongbox/curseforge_api.clj
src/strongbox/db.clj
src/strongbox/github_api.clj
src/strongbox/logging.clj
src/strongbox/main.clj
src/strongbox/nfo.clj
src/strongbox/specs.clj
src/strongbox/toc.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
src/strongbox/utils.clj
src/strongbox/zip.clj
test/strongbox/cli_test.clj
test/strongbox/core_test.clj
test/strongbox/nfo_test.clj

- how to filter by 'debug' when we run at 'info'? perhaps only display 'debug' if 'debug' messages are available.
- same for 'warn' and 'error'? no, we don't want nav jumping around. 'debug' is the first/last item and won't significantly affect the position of the others
- may not be possible. Have a play with the code vlaad came up with
- it works but styling is messed up because it is using 'text' instead of a 'label'. Doesn't seem possible to have a 'label' wrap at the moment. 
- does it have to be non-addon? what are we really trying to achieve here?
- user should be made aware that all is not right. if this is present in an addon's uber-button then app-level errors still need highlighting
- users may not be able to fix warnings but errors should be preventable/reportable
- happens …

4.0, per-addon logging

---

CHANGELOG.md
src/strongbox/addon.clj
src/strongbox/ui/jfx.clj
src/strongbox/utils.clj
test/strongbox/jfx_test.clj
test/strongbox/utils_test.clj

- believe it or not you can't: https://bugs.openjdk.java.net/browse/JDK-8091997
- I think it has something to do with the available height ...
- this leads to a bit of Weirdness

gui, 4.0 changes, release list on detail pane

---

CHANGELOG.md
TODO.md
cloverage.clj
src/strongbox/core.clj
src/strongbox/http.clj
src/strongbox/logging.clj
src/strongbox/main.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
test/strongbox/logging_test.clj

* logging, worked around issue with timbre 'timbre/with-config' and mutable 'timbre/*config* causing much Weirdness.
* core/reset-logging now brings all logging back into a predictable state.

4.0 bug fixes

---

CHANGELOG.md
README.md
TODO.md
src/strongbox/catalogue.clj
src/strongbox/config.clj
src/strongbox/core.clj
src/strongbox/specs.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
test/fixtures/user-config-4.1.json
test/strongbox/catalogue_test.clj
test/strongbox/config_test.clj
test/strongbox/core_test.clj

WoW Classic - The Burning Crusade support

---

CHANGELOG.md
TODO.md
src/strongbox/addon.clj
src/strongbox/github_api.clj
test/strongbox/addon_test.clj
test/strongbox/github_api_test.clj

I think I introduced it for readability...

github, removes the 'classic' suffix.

---

CHANGELOG.md
LICENCE.txt
TODO.md
project.clj
src/strongbox/core.clj
src/strongbox/logging.clj
src/strongbox/main.clj
src/strongbox/specs.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
test/strongbox/logging_test.clj

- the source for a report log is always 'app'
- anything else? changed addon directory? changed game track? shutting down?

Log level events

---

CHANGELOG.md
TODO.md
src/strongbox/catalogue.clj
src/strongbox/core.clj
src/strongbox/ui/jfx.clj
test/strongbox/catalogue_test.clj
test/strongbox/jfx_test.clj

- typically because of mismatched game tracks

ux, don't fail silently when installing addons

---

CHANGELOG.md
TODO.md
src/strongbox/catalogue.clj
src/strongbox/core.clj
src/strongbox/logging.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
src/strongbox/utils.clj
test/strongbox/catalogue_test.clj
test/strongbox/cli_test.clj

UX case for this is that if an addon has warnings/errors that are fixed after a refresh of the addons, then those warnings/errors should not be considered.
For example, if the game track for an addon directory is switched from "Retail, not-strict" to "Retail, strict" and non-retail addons are installed, then they will fail to find a match after the addons are refresh and voila - a legitimate warning. If the reverse happens and the strictness level is relaxed and a match is found then the warning indicator should go away.
- for example, if classic is installed in retail, or classic-bc is installed in classic
- user should be aware that things are not in a good state

gui, addon status only considered as far back as last refresh

---

CHANGELOG.md
src/strongbox/core.clj
src/strongbox/logging.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj

I found myself missing the split pane but can see how it wouldn't be for everybody.
The UX intent is that there is a niggling little reminder that errors/warnings may be present and how many. Clicking the warning button will display them in context with *all* addons - a per-addon error/warning button already exists and the addon detail pane already has a per-addon notice logger. There are also app-level errors that need surfacing to user's attention.
- "2 errors", "4 warnings" or just "split"
- dark theme must be considered as well
- or keep it, it's not doing much I think

gui, adds a 'split' option to bring the logging pane back

---

CHANGELOG.md
TODO.md
src/strongbox/catalogue.clj
src/strongbox/constants.clj
src/strongbox/core.clj
src/strongbox/http.clj
src/strongbox/joblib.clj
src/strongbox/main.clj
src/strongbox/tukui_api.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
src/strongbox/wowinterface.clj
src/strongbox/wowinterface_api.clj
test/strongbox/catalogue_test.clj
test/strongbox/cli_test.clj
test/strongbox/core_test.clj
test/strongbox/jfx_test.clj
test/strongbox/test_helper.clj
test/strongbox/tukui_api_test.clj
test/strongbox/wowinterface_test.clj

I fudged the nfo data to create a 'nfo catalogue' that lives below the user-catalogue and ... it seems to work well! if the main catalogue is unavailable (faked 500 response) or doesn't contain a match, it falls back to the match it had previously.
update: I got a wrong feeling from using the derived data (toc+nfo) as a 'catalogue' despite it being a fairly elegant solution. Instead I did a second pass on the 'unmatched' addons to see if certain required values could be safely polyfilled. This preserves the error messages that the addon failed to match, the list of addons that failed to match, etc and the tests don't need modifying.
- i.e. the user will be replacing the source of one addon for another

use nfo data (if it exists) when catalogue match not made

---

CHANGELOG.md
TODO.md
project.clj
src/strongbox/main.clj

* add --version parameter
* fixes annoying warning in transitive dependency.
* shuffles shutdown-hook and a call to reset-logging around so state doesn't exist when calling --help and --version, causing INFO logs to be emitted

add version parameter

---

CHANGELOG.md
TODO.md
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj

- more, single context menu expects/assumes a valid addon

gui, no options are available to select when no addons are selected

---

CHANGELOG.md
README.md
TODO.md
src/strongbox/curseforge_api.clj
src/strongbox/http.clj
test/strongbox/http_test.clj

It tends to flake out a bit towards the end of a long scrape. It's inconvenient for me but probably busting some caches on their end.
* http, adds 'download-with-backoff'
* curseforge-api, uses download-with-backoff while scraping api.
* curseforge-api, adds pause after each request.

be kinder to curseforge

---

CHANGELOG.md
TODO.md
src/strongbox/addon.clj
src/strongbox/catalogue.clj
src/strongbox/github_api.clj
src/strongbox/gitlab_api.clj
src/strongbox/nfo.clj
src/strongbox/specs.clj
src/strongbox/toc.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
src/strongbox/utils.clj
test/strongbox/addon_test.clj
test/strongbox/catalogue_test.clj
test/strongbox/cli_test.clj
test/strongbox/core_test.clj
test/strongbox/github_api_test.clj
test/strongbox/gitlab_api_test.clj
test/strongbox/jfx_test.clj
test/strongbox/nfo_test.clj
test/strongbox/test_helper.clj
test/strongbox/toc_test.clj

- can we rely on scraping this from other locations? I don't think so :(
- we already support source switching but it's not directly under the user's control
- I've added a "Find similar" context menu option that does a catalogue search against the addon's `label`. 
- It's the bare minimum but it kinda sorta *does* work - I've found curseforge addons with no alts in the wowi and github catalogues already.
- should I just use a uuid? I think something in the import logic now depends on the group-id being a URL :(
- looks like the mutual dependency checking relies on the group-id being predictable, so a unique uuid futzes with that
- nope, this is complex enough to warrant it's own dedicated task. It's also fine for now
- how big of a deal is this?
- not that big a deal. I've disabled the …

source switching

---

CHANGELOG.md
TODO.md
src/strongbox/config.clj
src/strongbox/specs.clj
src/strongbox/ui/cli.clj
test/fixtures/user-config-5.0.json
test/strongbox/config_test.clj

gui, change default column set

---

CHANGELOG.md
CONTRIBUTING.md
README.md
TODO.md
src/strongbox/github_api.clj
src/strongbox/toc.clj
src/strongbox/utils.clj

https://github.com/search?q=%22X-Github%22++extension%3Atoc&type=Code&ref=advsearch&l=&l=

add 'x-github' support

---

.joker
CHANGELOG.md
README.md
TODO.md
project.clj
src/strongbox/catalogue.clj
src/strongbox/core.clj
src/strongbox/db.clj
src/strongbox/specs.clj
src/strongbox/ui/check_combo_box.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
src/strongbox/utils.clj
test/strongbox/cli_test.clj
test/strongbox/core_test.clj
test/strongbox/utils_test.clj

- I kinda like having more options rather than less. keeping for now.

search across addon hosts

---

CHANGELOG.md
TODO.md
src/strongbox/core.clj
src/strongbox/db.clj
src/strongbox/specs.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
test/strongbox/cli_test.clj

clickable tags in search and installed panes

---

CHANGELOG.md
TODO.md
src/strongbox/nfo.clj
src/strongbox/specs.clj
src/strongbox/ui/cli.clj
src/strongbox/ui/jfx.clj
src/strongbox/utils.clj
test/strongbox/cli_test.clj
test/strongbox/nfo_test.clj
test/strongbox/utils_test.clj

gui, addon-detail, add mutual dependencies pane

---

CHANGELOG.md
src/strongbox/joblib.clj
src/strongbox/ui/cli.clj

but was instead getting a keyword.
this was because I was mixing create-job! (keyword job-ids) and create-addon-job! (keyset) usages.
all jobs are created with create-addon-job! now.

cli, fixed bug where gui was expecting a job-id as a keyset

---

CHANGELOG.md
TODO.md
src/strongbox/constants.clj
src/strongbox/ui/jfx.clj
src/strongbox/utils.clj
test/strongbox/utils_test.clj

jfx, adds patch release name as tooltip to 'WoW' column

---

CHANGELOG.md
TODO.md
src/strongbox/addon.clj
src/strongbox/toc.clj
src/strongbox/utils.clj
test/strongbox/core_test.clj
test/strongbox/test_helper.clj

When one addon *completely* replaces one or more _unrelated_ addons, those addons to be replaced are now uninstalled (rather than overwritten) so they don't become messy mutual dependencies.
This usecase is common when:
* the 'Find similar' feature is used to find and replace an installed addon with the same addon from the catalogue but from a different host.
* and the inverse, installing an addon from a file replacing an addon installed from the catalogue
* an addon bundle from wowinterface is installed

addons that are completely replaced are now uninstalled first.

---

CHANGELOG.md
LICENCE.txt
TODO.md
cloverage.clj
repl/strongbox/user.clj
src/strongbox/addon.clj
src/strongbox/cli.clj
src/strongbox/jfx.clj
src/strongbox/specs.clj
src/strongbox/toc.clj
src/strongbox/utils.clj
test/strongbox/addon_test.clj
test/strongbox/cli_test.clj
test/strongbox/core_test.clj
test/strongbox/jfx_test.clj
test/strongbox/toc_test.clj
test/strongbox/utils_test.clj

addon folder size 

---

CHANGELOG.md
TODO.md
src/strongbox/cli.clj
src/strongbox/core.clj
src/strongbox/jfx.clj
src/strongbox/specs.clj
test/strongbox/cli_test.clj
test/strongbox/core_test.clj
test/strongbox/jfx_test.clj

- try reconstructing a url and importing them?
- for example, if I unstar an addon on the installed pane, the search results are not updated
- looks like an unrelated error was preventing me from seeing this
- I *can't*, so how was it happening??
- it wasn't invalid, it was an installed addon merged with a catalogue summary, so just too much data.

user-catalogue, adds star button to installed addons tab

---

CHANGELOG.md
TODO.md
src/strongbox/catalogue.clj
src/strongbox/cli.clj
src/strongbox/core.clj
test/strongbox/cli_test.clj
test/strongbox/core_test.clj

user-catalogue, improvements now that github has it's own catalogue

---

CHANGELOG.md
TODO.md
src/strongbox/cli.clj
src/strongbox/core.clj
src/strongbox/jfx.clj
test/strongbox/core_test.clj

search, add 'clear' button

---

CHANGELOG.md
TODO.md
cloverage.clj
repl/strongbox/user.clj
src/strongbox/cli.clj
src/strongbox/config.clj
src/strongbox/constants.clj
src/strongbox/core.clj
src/strongbox/jfx.clj
src/strongbox/specs.clj
src/strongbox/utils.clj
test/fixtures/user-config-6.0.json
test/strongbox/cli_test.clj
test/strongbox/config_test.clj
test/strongbox/core_test.clj
test/strongbox/utils_test.clj

if a user-catalogue is more than 28 days old, it will trigger an automatic refresh and all addons that have been imported, or starred, will have it's user-catalogue entry matched against the *full* catalogue or imported again from online.

user-catalogue scheduled refreshes

---

CHANGELOG.md
TODO.md
src/strongbox/jfx.clj

gui tweaks

---

CHANGELOG.md
TODO.md
src/strongbox/cli.clj
src/strongbox/core.clj
src/strongbox/http.clj
src/strongbox/jfx.clj
src/strongbox/specs.clj
src/strongbox/utils.clj
test/strongbox/core_test.clj
test/strongbox/test_helper.clj
test/strongbox/utils_test.clj

- in fact, can the two share the same widget?

more stats

---

CHANGELOG.md
README.md
TODO.md
cloverage.clj
repl/strongbox/user.clj
src/strongbox/addon.clj
src/strongbox/catalogue.clj
src/strongbox/config.clj
src/strongbox/constants.clj
src/strongbox/core.clj
src/strongbox/specs.clj
src/strongbox/wowinterface_api.clj
test/fixtures/user-config-7.0.json
test/strongbox/catalogue_test.clj
test/strongbox/cli_test.clj
test/strongbox/config_test.clj
test/strongbox/core_test.clj
test/strongbox/utils_test.clj

- `catalogue/host-disabled?` and `catalogue/expand-summary`
- see `strongbox-catalogue-builder`
- see `strongbox-catalogue-builder`
- this will occur naturally when tukui addons are not present in any catalogue
- non-github, non-gitlab addons consult the catalogue to find the addon before importing it to fill in the missing gaps in data.
- disable anyway
- see `core/find-addon` 
- this will occur naturally when tukui addons are not present in any catalogue
- see `core/emergency-catalogue`
- otherwise they will appear in search results, will be importable.
- see `core/get-user-catalogue`
- see `addon/merge-toc-nfo` to remove curse and tukui from the available 'source-maps'
- see `core/import-exported-file`

removes tukui support

---

CHANGELOG.md
TODO.md
cloverage.clj
project.clj
repl/strongbox/user.clj
src/strongbox/cli.clj
src/strongbox/constants.clj
src/strongbox/core.clj
src/strongbox/jfx.clj
test/strongbox/cli_test.clj
test/strongbox/core_test.clj

- I don't think this would be good default behaviour. You search, you expect a full set of navigable results. It could be an opt-in preference to always sample search results, but this feels like a rabbit hole I'm going down, making shit up to solve imaginary problems.

search, sampling options

---

CHANGELOG.md
TODO.md
src/strongbox/jfx.clj
src/strongbox/utils.clj
test/strongbox/jfx_test.clj

I tried to make certain fields selectable for simple copying but it was an uphill battle against javafx. 
Instead I've opted for the (less than ideal) textual outputs 'json' and 'plain text' alongside the 'keyvals' mode.

gui, 'raw data' widget now has 'keyvals', 'json' and 'plain text' modes

---

CHANGELOG.md
project.clj
src/strongbox/config.clj
src/strongbox/core.clj
src/strongbox/jfx.clj
src/strongbox/main.clj
test/fixtures/user-config-7.0.json
test/strongbox/config_test.clj
test/strongbox/core_test.clj

Check for application update on program start (default true).

new preference 'check-for-update'

---

CHANGELOG.md
TODO.md
src/strongbox/addon.clj
src/strongbox/cli.clj
src/strongbox/core.clj
src/strongbox/jfx.clj
src/strongbox/nfo.clj
src/strongbox/specs.clj
test/strongbox/addon_test.clj
test/strongbox/cli_test.clj
test/strongbox/core_test.clj
test/strongbox/nfo_test.clj

Issue #433 
- huh - turns out the `overwrites-ignored?` and `overwrites-pinned?` checks happen *during download*. weird.
- good idea but: I don't have the time right now and I'm focusing on strongbox v8
- good idea but: I don't have the time right now and I'm focusing on strongbox v8

install addon from file, preserve 'ignore' and 'pin' flags
